version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "8082:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
    links:
      - mongo
    depends_on:
      - mongo
